<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'abeautifulsite' => array($vendorDir . '/abeautifulsite/simpleimage/src'),
    'OAuth\\Unit' => array($vendorDir . '/lusitanian/oauth/tests'),
    'OAuth' => array($vendorDir . '/lusitanian/oauth/src'),
    'Gregwar\\Image' => array($vendorDir . '/gregwar/image'),
);
